openapi: 3.0.3
info:
  title: API de Denuncias (Core)
  description: Gestion del ciclo de vida, asignacion y validacion de denuncias.
  version: 2.2.0

servers:
  - url: /api/denuncias
    description: Base URL relative to Gateway or Service

tags:
  - name: Denuncias
    description: Creacion y consulta de denuncias.
  - name: Workflow
    description: Asignacion, resolucion y validacion de denuncias.

paths:
  /:
    post:
      tags:
        - Denuncias
      summary: Crear denuncia
      operationId: crearDenuncia
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearDenunciaRequest'
      responses:
        '201':
          description: Creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DenunciaResumenResponse'
        '400':
          description: Solicitud invalida
        '401':
          description: No autorizado
        '409':
          description: Conflicto de datos

    get:
      tags:
        - Denuncias
      summary: Listar denuncias
      description: Filtra denuncias según el rol y entidad del usuario autenticado (extraído del token).
      operationId: listarDenuncias
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
      responses:
        '200':
          description: Lista de denuncias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DenunciaListadoResponse'

  /{denunciaId}:
    get:
      tags:
        - Denuncias
      summary: Obtener denuncia por id
      operationId: obtenerDenunciaPorId
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Denuncia encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DenunciaResponse'
        '404':
          description: Denuncia no encontrada

  /{denunciaId}/asignacion-entidad:
    post:
      tags:
        - Workflow
      summary: Asignar entidad responsable
      operationId: asignarEntidadADenuncia
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: entidad
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/EntidadResponsableEnum'
      responses:
        '200':
          description: Entidad asignada

  /{denunciaId}/asignacion-operador:
    post:
      tags:
        - Workflow
      summary: Asignar operador a denuncia
      operationId: asignarOperadorAdenuncia
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AsignarOperadorRequest'
      responses:
        '200':
          description: Operador asignado

  /{denunciaId}/iniciar-proceso:
    post:
      tags:
        - Workflow
      summary: Iniciar proceso de denuncia
      operationId: iniciarProcesoDenunciaOperadores
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Proceso iniciado

  /{denunciaId}/resolucion:
    post:
      tags:
        - Workflow
      summary: Registrar resolucion de denuncia
      operationId: resolverDenuncia
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarcarResolucionRequest'
      responses:
        '200':
          description: Denuncia resuelta y enviada a validacion

  /{denunciaId}/validacion:
    post:
      tags:
        - Workflow
      summary: Validar solucion de denuncia
      operationId: validarSolucionDenuncia
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidarSolucionRequest'
      responses:
        '200':
          description: Validacion procesada

  /{denunciaId}/historial-estados:
    get:
      tags:
        - Workflow
      summary: Historial de estados de la denuncia
      operationId: denunciaHistorialEstados
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Historial de estados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DenunciaEstadoHistorialResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    XCorrelationId:
      name: X-Correlation-Id
      in: header
      required: false
      schema:
        type: string
      description: Identificador de trazabilidad distribuida.

  schemas:
    # --- ENUMS ---
    CategoriaDenunciaEnum:
      type: string
      enum: [VIALIDAD, SANIDAD, ILUMINACION, JARDINERIA, AGUA, OTROS]

    EntidadResponsableEnum:
      type: string
      enum: [MUNICIPIO, EMPRESA_ELECTRICA, EMPRESA_AGUA_POTABLE]

    EstadoDenunciaEnum:
      type: string
      enum: [RECIBIDA, ASIGNADA, EN_PROCESO, EN_VALIDACION, RESUELTA]

    NivelAnonimatoEnum:
      type: string
      enum: [ANONIMO, PSEUDOANONIMO, REAL]

    # --- DTOs REQUESTS ---
    CrearDenunciaRequest:
      type: object
      required: [titulo, descripcion, categoriaDenuncia, latitud, longitud, nivelAnonimato]
      properties:
        titulo:
          type: string
          minLength: 5
          maxLength: 100
        descripcion:
          type: string
          minLength: 10
          maxLength: 500
        categoriaDenuncia:
          $ref: '#/components/schemas/CategoriaDenunciaEnum'
        latitud:
          type: number
          format: double
          minimum: -90.0
          maximum: 90.0
        longitud:
          type: number
          format: double
          minimum: -180.0
          maximum: 180.0
        nivelAnonimato:
          $ref: '#/components/schemas/NivelAnonimatoEnum'
        evidenciasIds:
          type: array
          items:
            type: string

    AsignarOperadorRequest:
      type: object
      required: [operadorId]
      properties:
        operadorId:
          type: integer
          format: int64
          description: Must be positive

    MarcarResolucionRequest:
      type: object
      required: [comentarioResolucion, evidenciasIds]
      properties:
        comentarioResolucion:
          type: string
          minLength: 10
          maxLength: 500
        evidenciasIds:
          type: array
          maxItems: 3
          items:
            type: string

    ValidarSolucionRequest:
      type: object
      required: [aprobada, comentarioObservacion]
      properties:
        aprobada:
          type: boolean
        comentarioObservacion:
          type: string
          minLength: 10
          maxLength: 500

    # --- DTOs RESPONSES ---
    EvidenciaDTO:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        contentType:
          type: string

    DenunciaResumenResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        mensaje:
          type: string

    DenunciaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        titulo:
          type: string
        descripcion:
          type: string
        categoriaDenuncia:
          $ref: '#/components/schemas/CategoriaDenunciaEnum'
        entidadResponsable:
          $ref: '#/components/schemas/EntidadResponsableEnum'
        latitud:
          type: number
          format: double
        longitud:
          type: number
          format: double
        nivelAnonimato:
          $ref: '#/components/schemas/NivelAnonimatoEnum'
        estadoDenuncia:
          $ref: '#/components/schemas/EstadoDenunciaEnum'
        ciudadanoId:
          type: integer
          format: int64
        operadorId:
          type: integer
          format: int64
        jefeId:
          type: integer
          format: int64
        comentarioResolucion:
          type: string
        comentarioObservacion:
          type: string
        evidenciaCreacionIds:
          type: array
          items:
            $ref: '#/components/schemas/EvidenciaDTO'
        evidenciasResolucionIds:
          type: array
          items:
            $ref: '#/components/schemas/EvidenciaDTO'
        creadoEn:
          type: string
          format: date-time
        actualizadoEn:
          type: string
          format: date-time

    DenunciaListadoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        titulo:
          type: string
        categoriaDenuncia:
          $ref: '#/components/schemas/CategoriaDenunciaEnum'
        entidadResponsable:
          $ref: '#/components/schemas/EntidadResponsableEnum'
        estadoDenuncia:
          $ref: '#/components/schemas/EstadoDenunciaEnum'
        ciudadanoId:
          type: integer
          format: int64
        operadorId:
          type: integer
          format: int64
        jefeId:
          type: integer
          format: int64
        creadoEn:
          type: string
          format: date-time

    EstadoCambio:
      type: object
      properties:
        estadoAnterior:
          $ref: '#/components/schemas/EstadoDenunciaEnum'
        estadoNuevo:
          $ref: '#/components/schemas/EstadoDenunciaEnum'
        actorId:
          type: integer
          format: int64
        ocurridoEn:
          type: string
          format: date-time

    DenunciaEstadoHistorialResponse:
      type: object
      properties:
        denunciaId:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/EstadoCambio'

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string

security:
  - BearerAuth: []
