openapi: 3.0.3
info:
  title: API de Denuncias (Core)
  description: Gestion del ciclo de vida, asignacion y validacion de denuncias.
  version: 2.2.0

servers:
  - url: /api/v1
    description: Gateway Base URL

tags:
  - name: Denuncias
    description: Creacion y consulta de denuncias.
  - name: Workflow
    description: Asignacion, resolucion y validacion de denuncias.

paths:
  /denuncias:
    post:
      tags:
        - Denuncias
      summary: Crear denuncia
      operationId: crearDenuncia
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearDenunciaRequest'
      responses:
        '201':
          description: Creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DenunciaResumenResponse'
        '400':
          description: Solicitud invalida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /denuncias/{denunciaId}:
    get:
      tags:
        - Denuncias
      summary: Obtener denuncia por id
      operationId: obtenerDenuncia
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Denuncia encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DenunciaResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Denuncia no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /denuncias/{denunciaId}/asignacion-entidad:
    post:
      tags:
        - Workflow
      summary: Asignar entidad responsable
      operationId: asignarEntidadResponsable
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: entidad
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/EntidadResponsableEnum'
      responses:
        '200':
          description: Entidad asignada
        '400':
          description: Solicitud invalida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Denuncia no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /denuncias/{denunciaId}/asignacion-operador:
    post:
      tags:
        - Workflow
      summary: Asignar operador a denuncia
      operationId: asignarOperador
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AsignarOperadorRequest'
      responses:
        '200':
          description: Operador asignado
        '400':
          description: Solicitud invalida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Denuncia no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /denuncias/{denunciaId}/iniciar-proceso:
    post:
      tags:
        - Workflow
      summary: Iniciar proceso de denuncia
      operationId: iniciarProceso
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: operadorId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Proceso iniciado
        '400':
          description: Solicitud invalida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Denuncia no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto de estado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /denuncias/{denunciaId}/resolucion:
    post:
      tags:
        - Workflow
      summary: Registrar resolucion de denuncia
      operationId: resolverDenuncia
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarcarResolucionRequest'
      responses:
        '200':
          description: Denuncia enviada a validacion
        '400':
          description: Solicitud invalida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Denuncia no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto de estado o evidencias
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /denuncias/{denunciaId}/validacion:
    post:
      tags:
        - Workflow
      summary: Validar solucion de denuncia
      operationId: validarSolucion
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidarSolucionRequest'
      responses:
        '200':
          description: Denuncia validada
        '400':
          description: Solicitud invalida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Denuncia no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto de estado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /denuncias/{denunciaId}/historial-estados:
    get:
      tags:
        - Workflow
      summary: Historial de estados de la denuncia
      operationId: historialEstados
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: denunciaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Historial de estados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DenunciaEstadoHistorialResponse'
        '401':
          description: No autorizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Denuncia no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    XCorrelationId:
      name: X-Correlation-Id
      in: header
      required: false
      schema:
        type: string
      description: Identificador de trazabilidad distribuida.

  schemas:
    EvidenceId:
      type: string
      description: ID de evidencia emitido por el microservicio de evidencias.
      example: "ev_9c1a"

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-11-24T10:00:00Z"
        status:
          type: integer
          example: 404
        error:
          type: string
          example: "Not Found"
        message:
          type: string
          example: "La denuncia con ID 123 no existe en el sistema."
        path:
          type: string
          example: "/api/v1/denuncias/123"

    NivelAnonimatoEnum:
      type: string
      enum: [ANONIMO, PSEUDOANONIMO, REAL]
      description: Nivel de anonimato elegido por el ciudadano.

    EstadoDenunciaEnum:
      type: string
      enum: [RECIBIDA, ASIGNADA, EN_PROCESO, EN_VALIDACION, RESUELTA]
      description: Estado actual de la denuncia.

    CategoriaDenunciaEnum:
      type: string
      enum: [VIALIDAD, SANIDAD, ILUMINACION, JARDINERIA, AGUA, OTROS]

    EntidadResponsableEnum:
      type: string
      enum: [MUNICIPIO, EMPRESA_ELECTRICA, EMPRESA_AGUA_POTABLE]

    CrearDenunciaRequest:
      type: object
      required: [titulo, descripcion, categoriaDenuncia, latitud, longitud, nivelAnonimato]
      properties:
        titulo:
          type: string
          example: "Fuga de agua en la calle 5"
        descripcion:
          type: string
          example: "Hay una fuga de agua potable frente al numero 123."
        categoriaDenuncia:
          $ref: '#/components/schemas/CategoriaDenunciaEnum'
        latitud:
          type: number
          format: double
          example: -34.6037
        longitud:
          type: number
          format: double
          example: -58.3816
        nivelAnonimato:
          $ref: '#/components/schemas/NivelAnonimatoEnum'
        ciudadanoId:
          type: integer
          format: int64
          example: 505
        evidenciasIds:
          type: array
          description: Evidencias del ciudadano asociadas a la denuncia.
          items:
            $ref: '#/components/schemas/EvidenceId'
          example: ["ev_9c1a", "ev_9c1b"]

    AsignarOperadorRequest:
      type: object
      required: [operadorId, asignadoPorId]
      properties:
        operadorId:
          type: integer
          format: int64
          example: 45
        asignadoPorId:
          type: integer
          format: int64
          example: 12

    MarcarResolucionRequest:
      type: object
      required: [comentarioResolucion, evidenciasIds]
      properties:
        comentarioResolucion:
          type: string
          example: "Fuga reparada, se reemplazo la tuberia."
        evidenciasIds:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/EvidenceId'
          example: ["ev_aa01", "ev_aa02"]
        resueltoPorId:
          type: integer
          format: int64
          example: 88

    ValidarSolucionRequest:
      type: object
      required: [aprobada, comentarioObservacion]
      properties:
        aprobada:
          type: boolean
          example: true
        comentarioObservacion:
          type: string
          example: "Solucion verificada correctamente."
        validadoPorId:
          type: integer
          format: int64
          example: 22

    EvidenciaDTO:
      type: object
      properties:
        id:
          type: string
          example: "ev_9c1a"
        url:
          type: string
          example: "https://storage.example.com/ev_9c1a"
        contentType:
          type: string
          example: "image/jpeg"

    DenunciaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 101
        titulo:
          type: string
          example: "Fuga de agua en la calle 5"
        descripcion:
          type: string
          example: "Hay una fuga de agua potable frente al numero 123."
        categoriaDenuncia:
          $ref: '#/components/schemas/CategoriaDenunciaEnum'
        entidadResponsable:
          $ref: '#/components/schemas/EntidadResponsableEnum'
        latitud:
          type: number
          format: double
          example: -34.6037
        longitud:
          type: number
          format: double
          example: -58.3816
        nivelAnonimato:
          $ref: '#/components/schemas/NivelAnonimatoEnum'
        estadoDenuncia:
          $ref: '#/components/schemas/EstadoDenunciaEnum'
        ciudadanoId:
          type: integer
          format: int64
          example: 505
        operadorId:
          type: integer
          format: int64
          example: 88
        comentarioResolucion:
          type: string
          example: "Fuga reparada."
        comentarioObservacion:
          type: string
          example: "Caso cerrado por el supervisor."
        evidenciaCreacionIds:
          type: array
          items:
            $ref: '#/components/schemas/EvidenciaDTO'
        evidenciasResolucionIds:
          type: array
          items:
            $ref: '#/components/schemas/EvidenciaDTO'
        creadoEn:
          type: string
          format: date-time
          example: "2025-11-24T10:00:00Z"
        actualizadoEn:
          type: string
          format: date-time
          example: "2025-11-24T12:00:00Z"

    DenunciaResumenResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 101
        mensaje:
          type: string
          example: "Denuncia creada"

    EstadoCambio:
      type: object
      properties:
        estadoAnterior:
          $ref: '#/components/schemas/EstadoDenunciaEnum'
        estadoNuevo:
          $ref: '#/components/schemas/EstadoDenunciaEnum'
        actorId:
          type: integer
          format: int64
          example: 12
        ocurridoEn:
          type: string
          format: date-time
          example: "2025-11-24T10:15:00Z"

    DenunciaEstadoHistorialResponse:
      type: object
      properties:
        denunciaId:
          type: integer
          format: int64
          example: 101
        items:
          type: array
          items:
            $ref: '#/components/schemas/EstadoCambio'

security:
  - BearerAuth: []
