openapi: 3.0.3
info:
  title: Microservicio de evidencias
  description: Servicio interno para registrar, confirmar y adjuntar evidencias a entidades.
  version: 2.0.0

servers:
  - url: /api/v1/evidencias
    description: Gateway evidencias path

tags:
  - name: Interno
    description: Endpoints S2S para manejo de evidencias.

paths:
  /interno/adjuntar:
    post:
      tags: [Interno]
      summary: Adjuntar evidencias a una entidad
      operationId: adjuntarEvidencias
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdjuntarEvidenciaRequest'
      responses:
        '200':
          description: Evidencias adjuntadas
        '400':
          description: Solicitud invalida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Evidencia no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflicto de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /interno/entidades/{tipo}/{id}/evidencias:
    get:
      tags: [Interno]
      summary: Listar evidencias por entidad
      operationId: obtenerEvidencias
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: tipo
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/EntidadTipoEnum'
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Lista de evidencias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EvidenciaInternaResponse'
        '400':
          description: Solicitud invalida
        '404':
          description: Entidad no encontrada

  /interno/{id}/confirmar:
    post:
      tags: [Interno]
      summary: Confirmar evidencia cargada
      operationId: confirmarCarga
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Evidencia confirmada
        '404':
          description: Evidencia no encontrada

  /interno/uploads:
    post:
      tags: [Interno]
      summary: Iniciar carga de evidencia
      operationId: crearIntencionDeCarga
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
        - name: filename
          in: query
          required: true
          schema:
            type: string
        - name: contentType
          in: query
          required: true
          schema:
            type: string
        - name: size
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Evidencia creada con URL firmada de subida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvidenciaInternaResponse'
        '400':
          description: Solicitud invalida
        '500':
          description: Error interno

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Internal-Service-Key

  parameters:
    XCorrelationId:
      name: X-Correlation-Id
      in: header
      required: false
      schema:
        type: string
      description: Identificador de trazabilidad distribuida.

  schemas:
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string

    EntidadTipoEnum:
      type: string
      enum: [DENUNCIA, RESOLUCION]

    EstadoEvidenciaEnum:
      type: string
      enum: [PENDIENTE_SUBIDA, SUBIDA, DISPONIBLE, BLOQUEADA]

    AdjuntarEvidenciaRequest:
      type: object
      required: [entidadTipo, entidadId, evidenciasIds]
      properties:
        entidadTipo:
          $ref: '#/components/schemas/EntidadTipoEnum'
        entidadId:
          type: integer
          format: int64
        evidenciasIds:
          type: array
          description: Lista de IDs de evidencias. Puede ser vacía pero no nula. Máximo 3.
          maxItems: 3
          items:
            type: string
        usuarioId:
          type: integer
          format: int64

    EvidenciaInternaResponse:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        contentType:
          type: string
        sizeBytes:
          type: integer
          format: int64

security:
  - BearerAuth: []
