openapi: 3.0.3
info:
  title: Microservicio de Notificaciones
  description: >
    Gestión centralizada de alertas (In-App, Correo, Push).
    Maneja el historial de mensajes para el usuario y provee endpoints internos
    para que otros microservicios (Auth, Denuncias) disparen eventos.
  version: 1.0.0

servers:
  - url: /api/v1/notificaciones
    description: Gateway Notifications Path

tags:
  - name: Buzon
    description: Endpoints para el usuario final (Ciudadano/Staff).
  - name: Interno
    description: Endpoints S2S (Service-to-Service) restringidos. Solo otros microservicios pueden llamarlos.

paths:
  # ----------------------------------------------------------------
  # BUZÓN DE USUARIO (HISTORIAL)
  # ----------------------------------------------------------------
  /me:
    get:
      tags:
        - Buzon
      summary: Obtener mis notificaciones
      description: Retorna el historial de alertas del usuario autenticado, ordenadas por fecha (más reciente primero).
      security:
        - BearerAuth: []
      parameters:
        - name: X-Correlation-Id
          in: header
          required: false
          schema: { type: string }
          description: Identificador de trazabilidad distribuida (propagado desde gateway).
        - name: page
          in: query
          schema: { type: integer, default: 0 }
        - name: soloNoLeidas
          in: query
          description: Si es true, filtra solo las que no se han abierto.
          schema: { type: boolean, default: false }
      responses:
        '200':
          description: Historial de notificaciones
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/NotificacionResponse'
                  noLeidasCount:
                    type: integer
                    description: Contador total de mensajes sin leer (para el numerito rojo en la campana).
                    example: 3
        '401':
          description: No autorizado

  /me/{id}/leida:
    patch:
      tags:
        - Buzon
      summary: Marcar como leída
      operationId: marcarLeida
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer, format: int64 }
        - name: X-Correlation-Id
          in: header
          required: false
          schema: { type: string }
          description: Identificador de trazabilidad distribuida (propagado desde gateway).
      responses:
        '204':
          description: Estado actualizado correctamente (Sin contenido)
        '404':
          description: Notificación no encontrada o no pertenece al usuario

  # ----------------------------------------------------------------
  # ENDPOINTS INTERNOS (INTEGRACIÓN)
  # ----------------------------------------------------------------
  /interno/disparar:
    post:
      tags:
        - Interno
      summary: Enviar nueva notificación (Uso interno)
      description: >
        Este endpoint es llamado por 'Denuncia Service' o 'Auth Service' cuando ocurre un evento.
        El servicio de notificaciones se encarga de:
        1. Guardar en BD (Historial).
        2. Enviar por WebSocket (Tiempo real).
        3. Enviar correo electrónico (Async).
      security:
        - ApiKeyAuth: [] # Seguridad entre servidores (puede ser mTLS o API Key interna)
      parameters:
        - name: X-Correlation-Id
          in: header
          required: false
          schema: { type: string }
          description: Identificador de trazabilidad distribuida (propagado desde gateway).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearNotificacionInternaRequest'
      responses:
        '202':
          description: Aceptada para procesamiento (Async)
        '400':
          description: Datos de evento inválidos

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Internal-Service-Key # Clave secreta compartida entre microservicios

  schemas:
    # --- ENUMS ---
    TipoEventoEnum:
      type: string
      enum:
        - DENUNCIA_CREADA       # Para Admins/Jefes
        - DENUNCIA_ASIGNADA     # Para Operador
        - DENUNCIA_RESUELTA     # Para Ciudadano (Final feliz)
        - DENUNCIA_RECHAZADA    # Para Ciudadano (Malas noticias)
        - VALIDACION_REQUERIDA  # Para Supervisor
        - BIENVENIDA_USUARIO    # Para Ciudadano nuevo

    PrioridadEnum:
      type: string
      enum: [ALTA, MEDIA, BAJA]

    # --- REQUESTS (INTERNO) ---
    CrearNotificacionInternaRequest:
      type: object
      required: [ usuarioDestinoId, tipoEvento, titulo, mensaje ]
      properties:
        usuarioDestinoId:
          type: integer
          format: int64
          description: ID del usuario que recibirá la alerta (extraído de Auth).
        tipoEvento:
          $ref: '#/components/schemas/TipoEventoEnum'
        entidadId:
          type: integer
          format: int64
          description: ID de la entidad relacionada - ej ID de la Denuncia). Sirve para hacer link.
        titulo:
          type: string
          example: "Tu denuncia ha sido resuelta"
        mensaje:
          type: string
          example: "El operador ha reparado el bache en la Av. Patria."
        canales:
          type: array
          items:
            type: string
            enum: [IN_APP, EMAIL, PUSH]
          default: [IN_APP]
          description: Por qué medios se debe intentar contactar.

    # --- RESPONSES ---
    NotificacionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        tipoEvento:
          $ref: '#/components/schemas/TipoEventoEnum'
        titulo:
          type: string
        mensaje:
          type: string
        leida:
          type: boolean
          example: false
        fechaCreacion:
          type: string
          format: date-time
        entidadId:
          type: integer
          description: ID para redirigir al usuario al detalle - ej ID denuncia.
