spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-auth
              uri: lb://ms-auth
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: ms-usuarios
              uri: lb://ms-usuarios
              predicates:
                - Path=/usuarios/**,/interno/usuarios/**

            - id: ms-denuncias
              uri: lb://ms-denuncias
              predicates:
                - Path=/api/denuncias/**

            - id: ms-evidencias
              uri: lb://ms-evidencias
              predicates:
                - Path=/interno/adjuntar/**,/interno/entidades/**,/interno/uploads/**,/interno/*/confirmar

  security:
    oauth2:
      resourceserver:
        jwt:
          # CORRECCIÓN 1: Apuntamos al contenedor ms-auth interno
          issuer-uri: http://ms-auth

server:
  port: 8081

eureka:
  instance:
    # CORRECCIÓN 2: Importante en la nube. Usa la IP interna del contenedor.
    prefer-ip-address: true
  client:
    service-url:
      # CORRECCIÓN 3: Apuntamos a http://ms-eureka (Puerto 80 implícito para Azure Ingress)
      defaultZone: http://ms-eureka/eureka/
    register-with-eureka: true