# Configuración de la aplicación ms-auth
spring:
  application:
    name: ms-auth
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ms_auth
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9092

eureka:
  instance:
    prefer-ip-address: false
    hostname: ms-auth.internal.wittyriver-e5cd2ef5.eastus.azurecontainerapps.io
    non-secure-port: 80
    non-secure-port-enabled: true
  client:
    service-url:
      defaultZone: http://ms-eureka.internal.wittyriver-e5cd2ef5.eastus.azurecontainerapps.io/eureka
    register-with-eureka: true

app:
  security:
    issuer: ${AUTH_ISSUER:http://localhost:9092}
    client:
      id: ${AUTH_CLIENT_ID:ds-web}
      redirect-uris: ${AUTH_REDIRECT_URIS:http://localhost:4200/dashboard,https://oauth.pstmn.io/v1/callback}
    reset-url: ${RESET_URL:http://localhost:5173/reset-password?token=}

ms-usuarios:
  url: ${MS_USUARIOS_URL:http://localhost:9091}
