# Configuración de la aplicación ms-denuncias
spring:
  application:
    name: ms-denuncias

  # Configuración de la base de datos PostgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres.your-id-on-supabase}
    password: ${DB_PASSWORD:your-password-on-supabase}
    url: ${DB_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres}
    hikari:
        maximum-pool-size: 5
        minimum-idle: 2
        max-lifetime: 60000

  # Configuración de JPA y Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Configuración del servidor y Eureka
server:
  port: 8083
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

