# Configuración de la aplicación ms-evidencias
spring:
  application:
    name: ms-evidencias

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ms_evidencias
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER:http://localhost:9092}

# Configuracion del storage de archivos en Supabase
app:
  supabase:
    url: ${SUPABASE_URL:}
    key: ${SUPABASE_ANON_KEY:}
    bucket: ${SUPABASE_BUCKET:Denuncias}

server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: true
