spring:
  application:
    name: ms-eureka

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
